<img src="images/keepcoding.png" width=200 align="left">

# Vectores

Imagina que estás jugando al billar. Es importante la fuerza con la que golpeas la bola, pero también la dirección en la que lo haces.

<img src="./images/billar.jpg" style="width: 250px;"/>

Los vectores en matemáticas son esas flechas que muestran cómo se mueve algo y con qué fuerza lo hace. Esto los diferencia de las magnitudes llamadas **escalares**, que se representan con un solo número. Veamos más ejemplos:

- La temperatura de una habitación es una magnitud escalar, por ejemplo, 24 grados
- El peso de una persona es un escalar, por ejemplo, 60kg
- El viento sopla con una determinada magnitud y en una dirección determinada, es una magnitud vectorial, por ejemplo 40km/h dirección sur
- La velocidad de un coche es una magnitud vectorial, por ejemplo, 100km/h dirección A Coruña

## 1. Definición

Un vector (real) de dimensión n es un ente matemático que viene representado por una tupla de números reales (que se llaman componentes del vector). 

<center>$v = (a_{1}, a_{2}, a_{3}, ... a_{n})$ donde $v \in {R}^{n}$</center>

Un vector también se puede ver desde el punto de vista de la geometría como vector geométrico. En este sentido, un vector es cualquier ente matemático que se puede representar mediante un segmento de recta orientado dentro del espacio euclidiano.

Para definir un vector necesitamos:

- Dirección, sentido, módulo y punto de aplicación

o bien

- Sus componentes $a_i$

<img src="./images/vector.png" alt="vector" style="width: 500px;"/>

Vemos este vector en el espacio bidimensional:

- Su módulo es la longitud de la flecha, que es un escalar. El módulo será mayor cuanto más grande sea la flecha
- Su dirección viene representada por la recta roja. Lo podemos medir mediante un ángulo con un eje horizontal imaginario
- Su sentido viene representado por la orientación de la flecha y hay dos posibles y opuestas para cada dirección
- Si se trata de un vector fijo en el plano, podemos representar su origen con un punto. Por ejemplo, el vector que va de A a B será $\vec{AB}$

Podemos representar el vector en un plano cartesiano bidimensional usando dos ejes coordenados:

<img src="./images/vector-coord.png" alt="vector" style="width: 500px;"/>


En este caso, además del módulo, dirección y sentido, vemos que el origen del vector se ha hecho coincidir con el origen de coordenadas y que podemos ver las componentes en cada uno de los ejes, por lo que $\vec{v}= (v_x, v_y)$.

En caso de estar en el espacio (tridimensional), necesitaríamos una componente más, y el dibujo también tendría una dimensión más. Sin embargo, la represntación con una flecha con módulo, dirección y sentido se mantiene.

<img src="./images/vector-coord-3.png" alt="vector" style="width: 500px;"/>

Podemos distinguir entre vectores fijos y libres: los últimos no están aplicados en un punto determinado, mientras que los primeros sí.

<div class="alert alert-block alert-success"> Notación: los vectores suelen representarse como $\vec{v}$ o con negrita y su módulo como $|v|$

## 2. Uso con python y operaciones elementales

Utilizaremos los vectores en Python para almacenar información (numérica) de todo tipo. 

In [2]:
!pip install numpy
import numpy as np
# Creación de un vector con numpy
v = np.array([2, 3, 4, 5, 6, 7])
print(v)

[2 3 4 5 6 7]


In [3]:
(2, 3, 4, 5, 6, 7)

(2, 3, 4, 5, 6, 7)

In [4]:
[2, 3, 4, 5, 6, 7]

[2, 3, 4, 5, 6, 7]

In [5]:
print(type(v))

<class 'numpy.ndarray'>


In [6]:
len(v)

6

In [7]:
# En el futuro vamos a poder guardar elementos multidimensionales, por lo que aprendemos a usar shape
v.shape

(6,)

### 2.1 Suma y resta de vectores

El **vector suma** está definido por:


<center>$[u_{1}, u_{2}, ..., u_{n}] + [v_{1}, v_{2}, ..., v_{n}] = [u_{1}+v_{1}, u_{2}+v_{2}, ..., u_{n}+v_{n}]$</center>

Para cualesquiera vectores **u**, **v**, **w**, se tiene:
* Propiedad asociativa: $(u+v)+w=u+(v+w)$
* Propiedad conmutativa: $u+v=v+u$


In [8]:
import numpy as np # !pip install numpy

x_np = np.array([1, 4, 2])
y_np = np.array([7, 4, 2])

x_np + y_np

array([8, 8, 4])

Es importante no tratar las listas de python como si fuesen vectores, porque el operador suma lo que hará será concatenarlas.

In [9]:
a = [1, 4, 2]
b = [7, 4, 2]

print(a+b)

[1, 4, 2, 7, 4, 2]


De forma similar, el vector resta se define como:

<center>$[u_{1}, u_{2}, ..., u_{n}] - [v_{1}, v_{2}, ..., v_{n}] = [u_{1}-v_{1}, u_{2}-v_{2}, ..., u_{n}-v_{n}]$</center>

Gráficamente el vector **-u** es el vector **u** con el sentido contrario de la flecha, por lo que podemos ver la resta como **u** - **v** = **u** + **-v** y usar el método gráfico que hemos visto para la suma.

In [11]:
y_np - x_np

array([6, 0, 0])

Que una de las componentes sea negativa, gráficamente, solo quiere decir que la componente de ese eje va a ir en el sentido contrario.


**IMPORTANTE**: No podemos sumar o restar vectores de distinta dimensión. Esto sería como intentar sumar una flecha en el plano con una en el espacio.

In [12]:
z_np = np.array([7, 4])
x_np + z_np

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## 2.2 Producto de un escalar por un vector

Dado un número $a$ y un vector $v$, la multiplicación viene definida por:
<br>
<center>$a \cdot (v_{1}, v_{2}, ... v_{n}) = (a \cdot v_{1}, a \cdot v_{2}, ... a \cdot v_{n})$</center>

Dado un vector **v** y dos números cualesquiera $\alpha$, $\beta \in \mathbb{R}$, se tiene:
* Propiedad asociativa: $\alpha$($\beta$**v**)=($\alpha$$\beta$)**v**  
* Propiedad distributiva: $\alpha$(**u**+**v**)=$\alpha$**u**+ $\alpha$**v**


Con numpy podemos usar la multiplicación directamente, pero no es el caso si tratamos con listas.

In [15]:
print(x_np)
3*x_np

[1 4 2]


array([ 3, 12,  6])

El vector resultante de la multiplicación por un escalar (que recordemos no es más que un número) es otro vector con la misma dirección, pero cuyo módulo se ha multiplicado por el escalar. En caso de que sea un número negativo, se invertiría también el sentido del vector.

## 2.3 Producto escalar o interior

El producto escalar o interior entre dos vectores tiene como resultado un escalar (un número). De nuevo, necesitamos que los dos vectores tengan la misma dimensión, o lo que es lo mismo, el mismo número de componentes.

Podemos imaginarlo como una manera de medir cuánto se parecen dos vectores o cuánto tienen en común en términos de dirección.

Pensemos en dos flechas que representan dos vectores. El producto escalar sería como multiplicar la longitud de una de esas flechas por la proyección de la otra flecha sobre la primera. Si las flechas van en la misma dirección, el producto escalar es grande porque tienen mucho en común. Si están en direcciones diferentes o perpendiculares, el producto escalar es más pequeño o incluso puede ser cero porque hay menos similitud entre ellas.

Por ejemplo, si estamos midiendo la fuerza que necesitas para empujar un objeto en la dirección exacta en la que queremos moverlo, el producto escalar de las fuerzas que aplicamos sería grande si empujas en la misma dirección que el movimiento y más pequeño si aplicamos la fuerza en una dirección diferente.


Considerando dos vectores $\overrightarrow{u}$ y $\overrightarrow{v}$, el producto escalar viene definido por:


<center>$\overrightarrow{u} \cdot \overrightarrow{v} = \sum_{i \in D}\overrightarrow{u}_{i} \cdot \overrightarrow{v}_{i} = u_{1} \cdot v_{1} + u_{2} \cdot v_{2} + ... u_{n} \cdot v_{n}$</center>

También puede escribirse de la siguiente forma:

<center>$\overrightarrow{u} \cdot \overrightarrow{v} = |\overrightarrow{u}||\overrightarrow{v}| \cos \theta $</center>

Donde las barras indican el módulo de los vectores (la magnitud de la flecha, lo veremos más adelante!) y $\theta$ es el ángulo que forman entre ellos (si los imaginamos como flechas).

Las **propiedades algebraicas del producto escalar** son:  
* **Propiedad conmutativa**: **u** · **v** = **v** · **u**  
* **Homogeneidad**: (α u) · v = α (u · v)  
* **Propiedad distributiva**: (v<sub>1</sub> + v<sub>2</sub>) · **x** = v<sub>1</sub> · **x** + v<sub>2</sub> · **x**  

Existe un operador en numpy para el producto escalar:

In [17]:
import numpy as np
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

v @ u

32

In [18]:
np.dot(u, v)

32

In [19]:
u = np.array([3, 2, 1])
v = np.array([4, 5])


¿Qué pasa si intentamos hacer el producto escalar con dos vectores de distinta dimensión?

In [20]:
v @ u

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

**Ejercicio**: Calcular el producto escalar sin usar numpy

In [21]:
u = [1, 2, 3, 4]
v = [7, 4, 5, 9]

In [23]:
def producto_escalar(u,v):
    accum = 0
    for n,v in zip(u,v):
        accum += n*v
    return accum
producto_escalar(u,v)

66

In [22]:
np.dot(u,v)

66

In [26]:
sum(i*k for i, k in zip(u,v))

66

In [30]:
for i, k in zip(u,v):
    print("Iteracion")
    print(i)
    print(k)

Iteracion
1
7
Iteracion
2
4
Iteracion
3
5
Iteracion
4
9


In [29]:
zip(u,v)

### 2.3.1 Vectores ortogonales

Dos vectores son ortogonales (geométricamente, perpendiculares) si y solo si su producto escalar es nulo. Si recordamos la fórmula del producto escalar, teníamos el coseno del ángulo que forman. Según la circunferencia trigonométrica, el coseno es 0 para un ángulo de 90 o 270.

Por tanto, si dos vectores tienen magnitud no nula (vamos a ver en un momento lo que es esto con más detalle) y su producto escalar es 0, son perpendiculares.

In [31]:
v1 = np.array([3, 4])
v2 = np.array([-4, 3])

v1 @ v2

0

### 2.4 Norma de un vector

La norma de un vector es básicamente una medida de su tamaño o longitud, es decir, de la magnitud de la flecha. 

En términos simples, para nosotros va a ser como calcular la distancia desde el origen (el punto de partida) hasta el extremo del vector.

Hay varios tipos de normas, y todas tienen que cumplir las siguientes propiedades:

* $\|v\|$ es un número real no negativo.  
* $\|v\|$ = 0 $\leftrightarrow$ **v**=0.   
* Para cualquier escalar $\alpha$, $\|\alpha\cdot v\|$ = $| \alpha | \cdot$ $\|v\|$.  
* $\|u+v\|$ ≤ $\|u\|$ + $\|v\|$ (desigualdad triangular)

Algunas normas comúnmente utilizadas son:

- Norma-1: $|x_1|+|x_2|+...+|x_n|$

- Norma-2: $\sqrt{|x_1|^2+|x_2|^2+...+|x_n|^2}$

- Norma-infinito: $\max(|x_1|, |x_2|,...,|x_n|)$

Utilizaremos sobre todo la norma 2, también llamada norma euclídea. Es la raíz cuadrada del producto escalar del vector por sí mismo. 

<center>$||v|| =+ \sqrt{v \cdot v} = (\sum_{i=1}^{n}x_{i}^2)^\frac{1}{2}$</center>

Por las propiedades del producto escalar, sabemos que va a ser un número positivo.

In [32]:
u_array = np.array(u)
v_array = np.array(v)
np.linalg.norm(u_array)

5.477225575051661

In [33]:
np.sqrt(u_array @ u_array)

5.477225575051661

Hay más formas de calcularla.

In [35]:
np.sqrt(sum(u_array*u_array))

5.477225575051661

### 3.1 Ejemplo: objeto en movimiento

Vamos a imaginar un objeto en movimiento con una velocidad inicial y una aceleración constante. Vamos a calcular su posición en diferentes momentos del tiempo utilizando ecuaciones de movimiento, que sabemos que son:

$\vec{x} = \vec{x_0} + \vec{v_0}t + {{1}\over{2}} \vec{a} t² $

Donde vamos a usar un sistema de 3 ejes cartesianos (x, y, z) y:

- $\vec{x}$ será la posición (vector!) en un instante de tiempo
- $\vec{x_0}$ será la posición inicial para t=0, que también es un vector (puesto que necesitamos saber las tres componentes)
- $\vec{v_0}$ es la velocidad inicial del objeto para t=0
- $\vec{a}$ es la aceleración del objeto, que vamos a tomar como una magnitud vectorial constante, es decir, que no depende del tiempo



In [38]:
import numpy as np

# Datos iniciales
x_0 = np.array([0, 0, 0])
v_0 = np.array([3, 4, 2])
a = np.array([0.5, -0.2, 1])
# Tiempo
t = 2
# Calcular la posición final utilizando las ecuaciones de movimiento

posicion_final = x_0 + v_0*t + 0.5*a*t**2

print("Posición final después de", t, "segundos:")
print("x: ", posicion_final[0])
print("x: ", posicion_final[1])
print("x: ", posicion_final[2])

Posición final después de 2 segundos:
x:  7.0
x:  7.6
x:  6.0


Podemos ver cómo cambia la posición final en función de la velocidad y posición iniciales.

### 3.2 Ejemplo: procesamiento de lenguaje natural

Además de múltiples ejemplos del mundo físico, los vectores tienen gran utilidad en el ámbito de PNL o procesamiento de lenguaje natural (NLP en inglés). 

El modelo más básico es la representación bag-of-words, que respresenta un texto como un conjunto no ordenado de palabras. No tiene en cuenta la relación entre las palabras, aunque sí que tiene en cuenta cuántas veces aparecen.

Veamos un ejemplo. Primero vamos a crear una función para obtener el vocabulario de las oraciones, es decir, todas las palabras distintas que aparecen:

In [39]:
import numpy as np

# Función para obtener el vocabulario único de las oraciones
def obtener_vocabulario(oraciones):
    palabras = set()
    for oracion in oraciones:
        palabras.update(oracion.split())
    return list(palabras)

Vamos a usar un par de oraciones de ejemplo:

In [46]:
# Ejemplo de oraciones
oraciones_ejemplo = [
    "El perro ladra",
    "Me gustan los perros",
    "Los perros y los perros son animales"
]

# Obtener el vocabulario único de las oraciones
vocabulario = obtener_vocabulario(oraciones_ejemplo)
vocabulario

['gustan',
 'ladra',
 'Me',
 'son',
 'animales',
 'perro',
 'los',
 'El',
 'perros',
 'Los',
 'y']

El siguiente paso sería crear un vector para cada oración, en función del vocabulario que hemos generado:

In [47]:
# Función para representar cada oración como un vector de frecuencia de palabras
def representar_oraciones(oraciones, vocabulario):
    representaciones = np.zeros((len(oraciones), len(vocabulario)))
    for i, oracion in enumerate(oraciones): # para cada oracion
        for palabra in oracion.split(): # dentro de cada oracion, cada palabra
            if palabra in vocabulario: # busco si está en el vocabulario
                indice = vocabulario.index(palabra) # si está, veo la posición en el vocabulario        
                representaciones[i][indice] += 1
    return representaciones
# Representar las oraciones como vectores de frecuencia de palabras

representaciones = representar_oraciones(oraciones_ejemplo, vocabulario)
# Imprimir resultados
print("Vocabulario: ", vocabulario)
for i, vector in enumerate(representaciones):
    print(f"Oración {i+1}: ", vector)

Vocabulario:  ['gustan', 'ladra', 'Me', 'son', 'animales', 'perro', 'los', 'El', 'perros', 'Los', 'y']
Oración 1:  [0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
Oración 2:  [1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0.]
Oración 3:  [0. 0. 0. 1. 1. 0. 1. 0. 2. 1. 1.]


In [45]:
representaciones

array([[0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.]])

In [43]:
vocabulario

['gustan',
 'ladra',
 'Me',
 'son',
 'animales',
 'gatos',
 'perro',
 'los',
 'El',
 'perros',
 'Los',
 'y']

Hay que tener en cuenta que normalmente en este tipo de representaciones se hace un tratamiento previo para quedarse con la raíz de la palabra, por ejemplo, "perro" y "perros" tendrían la misma raíz (esto se conoce como stemming). También se suelen quitar las palabras que no aportan significado, como "el", "la", "de", que se denominan "stop words". Existen librerías específicas que hacen este trabajo mucho más fácil, por ejemplo [nltk](https://www.nltk.org/)

In [51]:
!pip install nltk
import nltk

In [52]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /home/raquel/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /home/raquel/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /home/raquel/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /home/raquel/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /home/raquel/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |

True

In [53]:
import nltk
from nltk.tokenize import word_tokenize
tokens = word_tokenize(oraciones_ejemplo[0])

In [54]:
tokens

['El', 'perro', 'ladra']

Este tipo de representación es muy útil, por ejemplo, podríamos crear un clasificador para determinar si un email es o no spam, usando una muestra conocida para entrenar. Como es de esperar, trabajar con vectores (números) nos permite usar muchos más modelos.