<img src="images/keepcoding.png" width=200 align="left">

# Matrices

Al oír hablar de matrices es posible que nos imaginemos una malla bidimensional. En efecto, una matriz es un conjunto bidimensional de números, ordenados en filas y columnas. Como ya hemos visto por encima, las matrices nos van a servir para almacenar conjuntos de datos y para resolver sistemas de ecuaciones.

<img src="images/matrix.jpg" width=400 align="center">

## 1. Definición y operaciones básicas

Una matriz es un conjunto p-dimensional de números (elementos de la matriz) ordenados en filas (o renglones) y columnas. Si A es una matriz $m × n$, esto es, una matriz con $m$ filas y $n$ columnas, entonces la entrada escalar en la i-ésima y la j-ésima columna de $A$ se denota mediante $a_{ij}$ y se llama entrada $(i, j)$ de A.<br><br>

<center>$
  M=
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1j}  \\
   a_{21} & a_{22}  & ... & a_{2j}  \\
   ... & ...  & ... & ...  \\
   a_{i1} & a_{i2}  & ... & a_{ij}  \\
  \end{array} } \right]
$</center><br><br>  

Se dice que dos **matrices** son **iguales** si tienen el mismo tamaño, es decir, el mismo número de filas y de columnas, y sus columnas correspondientes son iguales.  

En python, podemos usar listas o arrays de Numpy para almacenar matrices, muy parecido a como hacíamos para los vectores (no deja de ser un vector con una dimensión más). La opción del array es la más cómoda y la que más usaremos. 

En numpy, vamos a usar la misma función que usábamos para los arrays, solo que ahora le añadimos una dimensión más (más adelante, le añadiremos más dimensiones aún!)

In [9]:
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6]])
print(type(A))
print(A)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [11]:
T = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
            [[21, 22, 23], [24, 25, 26], [27, 28, 29]]])

T.shape

(3, 3, 3)

No es recomendable usar `len()` cuando tratamos con matrices porque solo nos va a devolver una de las dimensiones.

In [10]:
print(len(A))
print(A.shape)

2
(2, 3)


### 1.1 Suma de matrices

Si A y B son matrices m × n, entonces la **suma** A + B es la matriz m × n cuyas columnas son las sumas de las columnas correspondientes de A y B. Es decir, es una suma elemento a elemento. Además, la suma A + B está definida sólo cuando A y B son del mismo tamaño.  

Para la resta se procede de modo similar, y podemos verlo como la suma de los elementos negativos de la segunda matriz.

Las propiedades de la suma de matrices son:

- Asociativa: (A + B) + C = A + (B + C)
- Conmutativa: A + B = B + A
- Elemento neutro: A + 0 = A, donde 0 es una matriz del mismo tamaño que A formada por ceros
- Elemento inverso: A + -A = 0

In [14]:
M1 = np.array([[1, 4], [2, 0]])
M2 = np.array([[-1, 2], [1, -2]])
print(M1)
print(M2)
M1 + M2

[[1 4]
 [2 0]]
[[-1  2]
 [ 1 -2]]


array([[ 0,  6],
       [ 3, -2]])

In [13]:
M1 - M2

array([[2, 2],
       [1, 2]])

### 1.2 Producto de una matriz por un escalar

Si r es un escalar y A es una matriz, entonces el múltiplo escalar $r \cdot A$ es la matriz cuyos elementos son los elementos de A multiplicados por r. El producto de una matriz y un escalar es:

- Asociativo: rsA = r(sA)
- Distributivo respecto a la suma de matrices: r(A+B) = rA + rB
- Tiene elemento neutro: 1A = A

In [15]:
M1

array([[1, 4],
       [2, 0]])

In [16]:
3*M1

array([[ 3, 12],
       [ 6,  0]])

### 1.3 Producto de matrices

Hasta ahora todo había sido bastante intuitivo, pero el producto de matrices se complica un poco. 

Si $A$ es una matriz $m × n$, y si $B$ es una matriz $n × p$ con columnas $b_1, b_2,... b_p$, entonces el **producto AB** es la matriz $m × p$ cuyas columnas son:<br><br>

<center>A*B= $
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{m1} & a_{m2}  & ... & a_{mn}  \\
  \end{array} } \right]
$ * $
  \left[ {\begin{array}{cc}
   b_{11} & b_{12}  & ... & b_{1p}  \\
   b_{21} & b_{22}  & ... & b_{2p}  \\
   ... & ...  & ... & ...  \\
   b_{n1} & b_{n2}  & ... & b_{np}  \\
  \end{array} } \right]
$ =<br><br> $
  \left[ {\begin{array}{cc}
   a_{11}\cdot b_{11}+ a_{12}\cdot b_{21} + ... + a_{1n}\cdot b_{n1}& a_{11}\cdot b_{12}+ a_{12}\cdot b_{22} + ... + a_{1n}\cdot b_{n2}  & ... & a_{11}\cdot b_{1p}+ a_{12}\cdot b_{2p} + ... + a_{1n}\cdot b_{np}  \\
   a_{21}\cdot b_{11}+ a_{22}\cdot b_{21} + ... + a_{2n}\cdot b_{n1}& a_{21}\cdot b_{12}+ a_{22}\cdot b_{22} + ... + a_{2n}\cdot b_{n2}  & ... & a_{21}\cdot b_{1p}+ a_{22}\cdot b_{2p} + ... + a_{2n}\cdot b_{np}  \\
   ... & ...  & ... & ...  \\
      a_{m1}\cdot b_{11}+ a_{m2}\cdot b_{21} + ... + a_{mn}\cdot b_{n1}& a_{m1}\cdot b_{12}+ a_{m2}\cdot b_{22} + ... + a_{mn}\cdot b_{n2}  & ... & a_{m1}\cdot b_{1p}+ a_{m2}\cdot b_{2p} + ... + a_{mn}\cdot b_{np}  \\
  \end{array} } \right]
$  
</center>

La notación para las dimensiones no es casual, para poder multiplicar las matrices necesitamos que el número de columnas de la primera matriz sea igual al número de filas de la segunda. El producto de matrices cumple:

- Asociatividad: A(BC) = (AB)C
- Distributividad respecto de la suma de matrices por la derecha: (A+B)C = AC + BC
- Distributividad respecto de la suma de matrices por la izquierda: C(A+B) = CA + CB

¿Echamos en falta algo habitual? El producto de matrices **no es conmutativo**.

In [19]:
A1 = np.array([[1, 4], [2, 0]])
A2 = np.array([[-1, 2], [1, -2]])

print(A1.shape)
print(A1)
print(A2.shape)
print(A2)

(2, 2)
[[1 4]
 [2 0]]
(2, 2)
[[-1  2]
 [ 1 -2]]


In [18]:
A1*A2

array([[-1,  8],
       [ 2,  0]])

**Ojo**, este no es el producto matricial, sino una multiplicación elemento a elemento, que además solo va a funcionar si las matrices tienen el mismo tamaño. Para el producto de matrices _de verdad_, usamos `.dot`

In [20]:
np.dot(A1, A2)

array([[ 3, -6],
       [-2,  4]])

Vemos que efectivamente el producto no es conmutativo. En general, a no ser que las matrices sean cuadradas (mismo número de filas que de columnas) tampoco va a ser posible multiplicar AB o BA indistintamente, sino solo una de ellas.

In [21]:
np.dot(A2, A1)

array([[ 3, -4],
       [-3,  4]])

In [22]:
B = np.array([1, 2, 3, 4])
B

array([1, 2, 3, 4])

In [23]:
B.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

## 2. Algunas matrices interesantes

### 2.1 Matrices cuadradas

Las matrices cuadradas son aquellas que tienen el mismo número de filas que de columnas.

### 2.2 Matrices triangulares


Una **matriz triangular** es una matriz cuadrada la cual tiene triángulos de ceros por encima o por debajo de la diagonal. En caso de que los valores ceros estén por encima de la diagonal se denomina **matriz triangular superior** y si es por debajo de la diagonal se denomina como **matriz triangular inferior**.<br><br>

**Matriz triangular superior**:

<center>$
  U_{nxm}=
  \left[ {\begin{array}{cc}
   1 & 4  & 6  \\
   0 & 2  & 2  \\
   0 & 0  & 1  \\
  \end{array} } \right]
$</center><br><br>

**Matriz triangular inferior**:

<center>$
  U_{nxm}=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 \\
   4 & 2  & 0\\
   7 & 3  & 1  \\
  \end{array} } \right]
$</center><br><br>

### 2.3 Matrices diagonales y la matriz identidad

La diagonal principal de una matriz cuadrada es la que empieza en el elemento (1,1), por ejemplo:

In [25]:
A = np.array([[1.345, 4, 5, 9], [2, 0.87, -3, -1], [-1, 10, 4, 4], [2, 3, 4, 6]])
print(A)

[[ 1.345  4.     5.     9.   ]
 [ 2.     0.87  -3.    -1.   ]
 [-1.    10.     4.     4.   ]
 [ 2.     3.     4.     6.   ]]


In [28]:
np.diag(A, 1)

array([ 4., -3.,  4.])


Se llama **matriz diagonal** a una matriz que solo tiene elementos en su diagonal principal. Si estos elementos son unos, se trata de la **matriz identidad**.

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
M1

array([[1, 4],
       [2, 0]])

In [34]:
M1.dot(np.identity(2))

array([[1., 4.],
       [2., 0.]])

In [35]:
np.identity(2).dot(M1)

array([[1., 4.],
       [2., 0.]])

In [30]:
np.identity(1)

array([[1.]])

In [29]:
# Podemos multiplicar la identidad por un escalar
897*np.identity(3)

array([[897.,   0.,   0.],
       [  0., 897.,   0.],
       [  0.,   0., 897.]])

Aunque no es la matriz identidad y no cumple sus propiedades, podemos crear una matriz de cualquier tamaño que solo tenga 1s en los elementos de la diagonal.

In [36]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((4, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
3*np.ones((4, 8))

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.]])

### 2.4 La matriz traspuesta

La traspuesta de una matriz es el resultado de intercambiar filas por columnas. 

In [40]:
A

array([[ 1.345,  4.   ,  5.   ,  9.   ],
       [ 2.   ,  0.87 , -3.   , -1.   ],
       [-1.   , 10.   ,  4.   ,  4.   ],
       [ 2.   ,  3.   ,  4.   ,  6.   ]])

In [42]:
A.T

array([[ 1.345,  2.   , -1.   ,  2.   ],
       [ 4.   ,  0.87 , 10.   ,  3.   ],
       [ 5.   , -3.   ,  4.   ,  4.   ],
       [ 9.   , -1.   ,  4.   ,  6.   ]])

In [43]:
np.transpose(A)

array([[ 1.345,  2.   , -1.   ,  2.   ],
       [ 4.   ,  0.87 , 10.   ,  3.   ],
       [ 5.   , -3.   ,  4.   ,  4.   ],
       [ 9.   , -1.   ,  4.   ,  6.   ]])

### 2.5 Matriz simétrica

Una **matriz cuadrada** va a ser **simétrica** si $A^T=A$, es decir si $A$ es igual a su propia matriz transpuesta.

In [44]:
C = np.array([[126, -66, 88], [-66, 58, -50], [88, -50, 46]])
print(C)

[[126 -66  88]
 [-66  58 -50]
 [ 88 -50  46]]


In [46]:
Ct = C.T
print(C.T)

[[126 -66  88]
 [-66  58 -50]
 [ 88 -50  46]]


In [47]:
np.array_equal(C, Ct)

True

### 2.6 La matriz inversa

Este apartado solo aplica a **matrices cuadradas**, es decir, con el mismo número de filas que de columnas. La inversa de una matriz A se representa como $A^{-1}$ y es otra matriz tal que $A \cdot A^{−1} = I$ donde I es la matriz identidad de la misma dimensión (es decir, mismo número de filas/columnas).

No todas las matrices cuadradas tienen inversa, las que no tienen son las llamadas matrices singulares, y veremos más adelante algunas de sus características.

Hay varias formas de calcular la inversa de una matriz, la más sencilla seguramente sea la de eliminación guassiana. El cálculo de una matriz inversa es un proceso un poco engorroso, pero por suerte podemos utilizar numpy.

In [48]:
A = np.array([[0, 1, 2], [1, 0, 3], [4, -3, 8]])
print(A)
inv_A = np.linalg.inv(A)
inv_A

[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]


array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

In [49]:
np.dot(A, inv_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.dot(inv_A, A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 2.7 Ejemplo: matriz de adyacencia de un grafo

Imaginamos un grafo con N nodos o vértices, podemos representar todas las conexiones posibles entre esos nodos utilizando una matriz cuadrada de tamaño N por N. Cada fila y columna en la matriz corresponde a un nodo en particular. Esta es la llamada matriz de adyacencia de un grafo.

Si es un grafo no dirigido, es decir, las conexiones entre nodos no tienen una dirección específica, la matriz de adyacencia será simétrica respecto a su diagonal principal. Los valores en la matriz representan si existe o no una conexión entre los nodos.

**Ejercicio:** Escribe la matriz de adyacencia del siguiente grafo:

<img src="images/grafo.png" width=400 align="center">

In [78]:
import numpy as np
# Creamos una matriz de ceros 4x4
matriz_adyacencia = np.zeros((4, 4), dtype = int)

# Establecemos las conexiones en la matriz
conexiones = [(0, 1), (1, 2), (2, 3), (0, 3)]

for conexion in conexiones:
    fila, columna = conexion # valores de la tupla (fila, columna)
    matriz_adyacencia[fila][columna] = 1
    matriz_adyacencia[columna][fila] = 1

print(matriz_adyacencia)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [76]:
A

array([[0, 1, 1],
       [1, 0, 3],
       [1, 2, 3]])

In [75]:
A[2] = np.array([1, 2, 3])

In [69]:
A[0,2]

2

In [59]:
v = np.array([1,2,3])

In [60]:
v[0]

1

In [82]:
li = {'a', 'b'}
fila, columna = li

In [83]:
fila

'a'

In [84]:
columna

'b'

### 3 Factorización LU

La factorización LU, llamada así por sus factores L (lower triangular) y U (upper triangular), es un método de descomposición de una matriz en el producto de dos matrices triangulares. Sea $A$ una matriz, entonces buscamos:  
 
<center>$A = LU$</center>

donde $L$ y $U$ son matrices inferiores y superiores triangulares respectivamente.  

Si pensamos en una matriz cuadrada:<br><br>
$
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{n1} & a_{n2}  & ... & a_{nn}  \\
  \end{array} } \right]
$ =
$
  \left[ {\begin{array}{cc}
   1      & 0       & 0    & ... & 0  \\
   l_{21} & 1       & 0    & ... & 0  \\
   ...    & ...     & ...  & ... & ... \\
   l_{n1} & l_{n2}  & ...  & ... & 1  \\
  \end{array} } \right]
$* $
  \left[ {\begin{array}{cc}
   u_{11} & u_{12} & u_{13} & ... & u_{1n}  \\
   0      & u_{22} & u_{23} & ... & b_{2n}  \\
   ...    & ...    & ...    & ... & ...     \\
   0      & 0      & ...    & ... & u_{nn}  \\
  \end{array} } \right]
$
  
Si la matriz A es invertible, es decir, tiene inversa, las matrices L y U son únicas.  

El proceso de factorización LU se utiliza comúnmente en la resolución de sistemas de ecuaciones lineales, ya que facilita la resolución de sistemas de ecuaciones mediante la sustitución hacia adelante (forward substitution) y la sustitución hacia atrás (backward substitution).

Para realizar la factorización LU, se utilizan operaciones de eliminación gaussiana para transformar la matriz original en las matrices L y U. Esto se hace aplicando operaciones elementales de fila para llevar la matriz original a una forma triangular. Las operaciones utilizadas para convertir A en U también se aplican a una matriz 
L inicialmente igual a la identidad, de tal manera que L guarda la información de las operaciones realizadas.

La factorización LU tiene aplicaciones en la resolución de sistemas de ecuaciones lineales, cálculos de determinantes, inversión de matrices y en la resolución numérica de ecuaciones diferenciales, entre otros campos matemáticos y científicos. Al descomponer una matriz en dos matrices triangulares, se simplifica la resolución de sistemas de ecuaciones lineales y otros problemas algebraicos.

In [3]:
from scipy import linalg 
import numpy as np

A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [4]:
_, l, u = linalg.lu(A)

In [5]:
l

array([[1.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        ],
       [0.5       , 0.33333333, 1.        ]])

In [6]:
u

array([[2.        , 1.        , 1.        ],
       [0.        , 1.5       , 0.5       ],
       [0.        , 0.        , 1.33333333]])

In [7]:
np.dot(l,u)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

## 4 Determinantes

El determinante $|A|$ de una matriz cuadrada  $A$ es un número que obtenemos a partir de los elementos de la matriz, y que nos dará una idea de cómo estos elementos se relacionan entre ellos.

Con Numpy, podemos calcular el determinante fácilmente usando `linalg.det`.

In [8]:
A

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [9]:
np.linalg.det(A)

4.0

### 4.1 Matrices inversas e invertibles

Una **matriz** $A$ es **invertible** si y sólo si $|A|≠0$.

In [11]:
np.linalg.inv(A)

array([[ 0.75, -0.25, -0.25],
       [-0.25,  0.75, -0.25],
       [-0.25, -0.25,  0.75]])

In [12]:
A[2] = np.array([2, 1, 1])

In [13]:
A

array([[2, 1, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [14]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [15]:
np.linalg.pinv(A)

array([[ 0.31818182, -0.36363636,  0.31818182],
       [-0.18181818,  0.63636364, -0.18181818],
       [ 0.04545455,  0.09090909,  0.04545455]])